openapi: 3.0.1
info:
  title: StockList API
  description: >-
    This is a simple server StockList server.
  contact:
    email: anshikjain18@gmail.com
  version: '1.0'
externalDocs:
  description: Find out more about StockList
  url: https:///swagger.io
servers:
  - url: http://localhost:5000
tags:
  - name: auth
    description: Operations about user authentication
paths:
  /auth/signup:
    post:
      tags:
        - auth
      summary: Signs up a new user into the system
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignup'
      responses:
        '201':
          description: Signed up successfully
        '409':
          description: Username already exists
  /auth/login:
    post:
      tags:
        - auth
      summary: Logs user into the system
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Logged in successfully
        '422':
          description: Invalid email/password
  /auth/logout:
    post:
      tags:
        - auth
      summary: Logs out user from the system
      security:
        - BearerAuth: []
      operationId: logout
      responses:
        '200':
          description: Logged out successfully
  /auth/delete:
    delete:
      tags:
        - auth
      summary: Deletes user from the system
      security:
        - BearerAuth: [ ]
      operationId: delete_account
      responses:
        '204':
          description: User deleted successfully
        '422':
          description: Unable to delete user
components:
  schemas:
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UserSignup:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
